window.TRANSLATIONS = {
  id: {
    brand_name: "Kedai",
    menu_title: "Menu Kami",
    see_menu: "Lihat Menu",
    order_now: "Pesan Sekarang",
    about_title: "Tentang Kami",
    contact_title: "Hubungi Kami",
    search_placeholder: "Cari menu makanan/minuman/snack...",
    footer_brand: "Kedai Mae",
    footer_desc: "Menghidangkan makanan dan minuman berkualitas dengan cita rasa autentik sejak 2024.",
    footer_quicklinks: "Tautan Cepat",
    footer_contact: "Kontak Kami",
    catering_title: "Pemesanan Catering",
    catering_name_label: "Nama Pemesan:",
    catering_name_placeholder: "Masukkan nama Anda",
    catering_phone_label: "No. Telepon/WA:",
    catering_phone_placeholder: "08xxxxxxxxxx",
    catering_event_label: "Jenis Acara:",
    catering_event_placeholder: "Contoh: Arisan, Meeting, Ulang Tahun, dll",
    catering_date_label: "Tanggal Acara:",
    catering_menu_label: "Menu Pilihan:",
    catering_menu_placeholder: "Contoh: Nasi Goreng 20 porsi, Ayam Bakar 15 porsi, dll",
    catering_total_label: "Total Porsi:",
    catering_total_placeholder: "Minimal 10",
    catering_notes_label: "Catatan Tambahan:",
    catering_notes_placeholder: "Permintaan khusus, alergi, dll (opsional)",
    catering_estimasi_label: "Estimasi Harga (Rp):",
    catering_submit: "Kirim Permintaan Catering",
    catering_why_title: "Kenapa pesan catering di Kedai Mae?",
    catering_why_1: "✔️ Menu bisa custom sesuai kebutuhan",
    catering_why_2: "✔️ Harga spesial untuk jumlah besar",
    catering_why_3: "✔️ Gratis konsultasi menu & porsi",
    catering_why_4: "✔️ Cocok untuk arisan, kantor, ulang tahun, dll",
    nav_home: "Beranda",
    nav_menu: "Menu",
    nav_about: "Tentang",
    nav_contact: "Kontak",
    nav_catering: "Catering",
    footer_link_home: "Beranda",
    footer_link_menu: "Menu",
    footer_link_about: "Tentang",
    footer_link_contact: "Kontak",
    footer_link_catering: "Catering",
    form_error_name: "Nama wajib diisi.",
    form_error_phone: "Nomor telepon tidak valid.",
    form_error_date: "Tanggal wajib diisi.",
    form_error_date_past: "Tanggal tidak boleh lampau.",
    form_error_menu: "Menu pilihan wajib diisi.",
    form_error_total: "Minimal 10 porsi.",
    notif_success: "Permintaan catering berhasil dikirim! Kami akan segera menghubungi Anda.",
    notif_cart_empty: "Keranjang Anda kosong. Silakan tambahkan item terlebih dahulu.",
    notif_cart_add: "ditambahkan ke keranjang",
    notif_cart_stock: "Stok habis!",
    notif_cart_over: "Jumlah di keranjang melebihi stok!",
    notif_order_name: "Silakan masukkan nama Anda",
    notif_order_qty: "Jumlah pesanan tidak valid",
    notif_order_sent: "Pesanan berhasil dikirim! Silakan cek WhatsApp Anda untuk konfirmasi.",
    notif_payment_redirect: "Anda akan diarahkan ke halaman pembayaran otomatis.",
    hero_title: "Selamat Datang di",
    hero_subtitle: "Menghidangkan makanan dan minuman berkualitas dengan cita rasa autentik sejak 2024",
    about_brand: "Kedai Kita",
    about_desc1: "Kedai Mae adalah tempat terbaik untuk menikmati makanan dan minuman berkualitas dengan cita rasa autentik.",
    about_desc2: "Kami selalu menggunakan bahan segar dan resep pilihan untuk setiap hidangan.",
    about_desc3: "Nikmati suasana nyaman dan pelayanan ramah di Kedai Mae.",
    tab_makanan: "Makanan",
    tab_minuman: "Minuman",
    tab_snack: "Makanan Ringan",
    contact_address_label: "Alamat",
    contact_address: "Jl. Raya Kedai No. 123, Kota Kita",
    contact_phone_label: "Telepon",
    contact_phone: "087878177527",
    contact_email_label: "Email",
    contact_email: "info@kedaimae.com",
    spicy_not: "Tidak Pedas",
    spicy_medium: "Sedang",
    spicy_hot: "Pedas",
    spicy_very_hot: "Pedas Banget",
    footer_copyright: "&copy; 2025 Kedai Mae. Semua Hak Dilindungi.",
  },
  en: {
    brand_name: "Kedai",
    menu_title: "Our Menu",
    see_menu: "See Menu",
    order_now: "Order Now",
    about_title: "About Us",
    contact_title: "Contact Us",
    search_placeholder: "Search food/drink/snack menu...",
    footer_brand: "Kedai Mae",
    footer_desc: "Serving quality food and beverages with authentic taste since 2024.",
    footer_quicklinks: "Quick Links",
    footer_contact: "Contact Us",
    catering_title: "Catering Order",
    catering_name_label: "Name:",
    catering_name_placeholder: "Enter your name",
    catering_phone_label: "Phone/WhatsApp:",
    catering_phone_placeholder: "08xxxxxxxxxx",
    catering_event_label: "Event Type:",
    catering_event_placeholder: "E.g.: Gathering, Meeting, Birthday, etc.",
    catering_date_label: "Event Date:",
    catering_menu_label: "Menu Selection:",
    catering_menu_placeholder: "E.g.: Fried Rice 20 portions, Grilled Chicken 15 portions, etc.",
    catering_total_label: "Total Portions:",
    catering_total_placeholder: "Minimum 10",
    catering_notes_label: "Additional Notes:",
    catering_notes_placeholder: "Special requests, allergies, etc. (optional)",
    catering_estimasi_label: "Estimated Price (Rp):",
    catering_submit: "Send Catering Request",
    catering_why_title: "Why order catering at Kedai Mae?",
    catering_why_1: "✔️ Custom menu as needed",
    catering_why_2: "✔️ Special price for large orders",
    catering_why_3: "✔️ Free menu & portion consultation",
    catering_why_4: "✔️ Suitable for gatherings, office, birthdays, etc.",
    nav_home: "Home",
    nav_menu: "Menu",
    nav_about: "About",
    nav_contact: "Contact",
    nav_catering: "Catering",
    footer_link_home: "Home",
    footer_link_menu: "Menu",
    footer_link_about: "About",
    footer_link_contact: "Contact",
    footer_link_catering: "Catering",
    form_error_name: "Name is required.",
    form_error_phone: "Invalid phone number.",
    form_error_date: "Date is required.",
    form_error_date_past: "Date cannot be in the past.",
    form_error_menu: "Menu selection is required.",
    form_error_total: "Minimum 10 portions.",
    notif_success: "Catering request sent successfully! We will contact you soon.",
    notif_cart_empty: "Your cart is empty. Please add items first.",
    notif_cart_add: "added to cart",
    notif_cart_stock: "Out of stock!",
    notif_cart_over: "Cart quantity exceeds stock!",
    notif_order_name: "Please enter your name",
    notif_order_qty: "Invalid order quantity",
    notif_order_sent: "Order sent successfully! Please check your WhatsApp for confirmation.",
    notif_payment_redirect: "You will be redirected to the payment page.",
    hero_title: "Welcome to",
    hero_subtitle: "Serving quality food and beverages with authentic taste since 2024",
    about_brand: "Our Place",
    about_desc1: "Kedai Mae is the best place to enjoy quality food and drinks with authentic flavors.",
    about_desc2: "We always use fresh ingredients and selected recipes for every dish.",
    about_desc3: "Enjoy a cozy atmosphere and friendly service at Kedai Mae.",
    tab_makanan: "Food",
    tab_minuman: "Drinks",
    tab_snack: "Snacks",
    contact_address_label: "Address",
    contact_address: "Jl. Raya Kedai No. 123, Kota Kita",
    contact_phone_label: "Phone",
    contact_phone: "087878177527",
    contact_email_label: "Email",
    contact_email: "info@kedaimae.com",
    spicy_not: "Not Spicy",
    spicy_medium: "Medium",
    spicy_hot: "Spicy",
    spicy_very_hot: "Very Spicy",
    footer_copyright: "&copy; 2025 Kedai Mae. All Rights Reserved.",
  },
  ko: {
    brand_name: "케다이",
    menu_title: "메뉴",
    see_menu: "메뉴 보기",
    order_now: "지금 주문하기",
    about_title: "회사 소개",
    contact_title: "문의하기",
    search_placeholder: "음식/음료/간식 메뉴 검색...",
    footer_brand: "케다이 메이",
    footer_desc: "2024년부터 정통의 맛으로 고품질 음식과 음료를 제공합니다.",
    footer_quicklinks: "빠른 링크",
    footer_contact: "문의처",
    catering_title: "케이터링 주문",
    catering_name_label: "이름:",
    catering_name_placeholder: "이름을 입력하세요",
    catering_phone_label: "전화/WhatsApp:",
    catering_phone_placeholder: "08xxxxxxxxxx",
    catering_event_label: "행사 종류:",
    catering_event_placeholder: "예: 모임, 회의, 생일 등",
    catering_date_label: "행사 날짜:",
    catering_menu_label: "메뉴 선택:",
    catering_menu_placeholder: "예: 볶음밥 20인분, 구운 치킨 15인분 등",
    catering_total_label: "총 인분:",
    catering_total_placeholder: "최소 10",
    catering_notes_label: "추가 메모:",
    catering_notes_placeholder: "특별 요청, 알레르기 등 (선택 사항)",
    catering_estimasi_label: "예상 가격 (Rp):",
    catering_submit: "케이터링 요청 보내기",
    catering_why_title: "왜 케다이 메이에서 케이터링을 주문하나요?",
    catering_why_1: "✔️ 필요에 따라 맞춤 메뉴",
    catering_why_2: "✔️ 대량 주문 시 특별 가격",
    catering_why_3: "✔️ 무료 메뉴 및 인분 상담",
    catering_why_4: "✔️ 모임, 사무실, 생일 등에 적합",
    nav_home: "홈",
    nav_menu: "메뉴",
    nav_about: "소개",
    nav_contact: "문의",
    nav_catering: "케이터링",
    footer_link_home: "홈",
    footer_link_menu: "메뉴",
    footer_link_about: "소개",
    footer_link_contact: "문의",
    footer_link_catering: "케이터링",
    form_error_name: "이름은 필수입니다.",
    form_error_phone: "유효하지 않은 전화번호입니다.",
    form_error_date: "날짜는 필수입니다.",
    form_error_date_past: "날짜는 과거일 수 없습니다.",
    form_error_menu: "메뉴 선택은 필수입니다.",
    form_error_total: "최소 10인분.",
    notif_success: "케이터링 요청이 성공적으로 전송되었습니다! 곧 연락드리겠습니다.",
    notif_cart_empty: "장바구니가 비어 있습니다. 먼저 항목을 추가하세요.",
    notif_cart_add: "장바구니에 추가됨",
    notif_cart_stock: "재고 없음!",
    notif_cart_over: "장바구니 수량이 재고를 초과했습니다!",
    notif_order_name: "이름을 입력하세요",
    notif_order_qty: "유효하지 않은 주문 수량",
    notif_order_sent: "주문이 성공적으로 전송되었습니다! WhatsApp에서 확인하세요.",
    notif_payment_redirect: "결제 페이지로 이동합니다.",
    hero_title: "어서오세요",
    hero_subtitle: "2024년부터 정통의 맛으로 고품질 음식과 음료를 제공합니다.",
    about_brand: "우리 가게",
    about_desc1: "케다이 메이는 정통의 맛으로 고품질 음식과 음료를 즐길 수 있는 최고의 장소입니다.",
    about_desc2: "항상 신선한 재료와 엄선된 레시피만을 사용합니다.",
    about_desc3: "케다이 메이에서 아늑한 분위기와 친절한 서비스를 즐기세요.",
    tab_makanan: "음식",
    tab_minuman: "음료",
    tab_snack: "간식",
    contact_address_label: "주소",
    contact_address: "Jl. Raya Kedai No. 123, Kota Kita",
    contact_phone_label: "전화",
    contact_phone: "087878177527",
    contact_email_label: "이메일",
    contact_email: "info@kedaimae.com",
    spicy_not: "맵지 않음",
    spicy_medium: "보통",
    spicy_hot: "매움",
    spicy_very_hot: "아주 매움",
    footer_copyright: "&copy; 2025 케다이 메이. 모든 권리 보유.",
  },
  ja: {
    brand_name: "ケダイ",
    menu_title: "メニュー",
    see_menu: "メニューを見る",
    order_now: "今すぐ注文",
    about_title: "私たちについて",
    contact_title: "お問い合わせ",
    search_placeholder: "料理/飲み物/スナックを検索...",
    footer_brand: "ケダイ メイ",
    footer_desc: "2024年から本格的な味で高品質な料理と飲み物を提供しています。",
    footer_quicklinks: "クイックリンク",
    footer_contact: "お問い合わせ先",
    catering_title: "ケータリング注文",
    catering_name_label: "お名前：",
    catering_name_placeholder: "お名前を入力してください",
    catering_phone_label: "電話/WhatsApp：",
    catering_phone_placeholder: "08xxxxxxxxxx",
    catering_event_label: "イベント種類：",
    catering_event_placeholder: "例：集まり、会議、誕生日など",
    catering_date_label: "イベント日：",
    catering_menu_label: "メニュー選択：",
    catering_menu_placeholder: "例：チャーハン20人分、焼き鳥15人分など",
    catering_total_label: "合計人数：",
    catering_total_placeholder: "最低10",
    catering_notes_label: "追加メモ：",
    catering_notes_placeholder: "特別なリクエスト、アレルギーなど（任意）",
    catering_estimasi_label: "見積もり価格 (Rp)：",
    catering_submit: "ケータリングリクエストを送信",
    catering_why_title: "なぜケダイメイでケータリングを注文するのか？",
    catering_why_1: "✔️ 必要に応じてカスタムメニュー",
    catering_why_2: "✔️ 大量注文で特別価格",
    catering_why_3: "✔️ 無料メニュー＆人数相談",
    catering_why_4: "✔️ 集まり、オフィス、誕生日などに最適",
    nav_home: "ホーム",
    nav_menu: "メニュー",
    nav_about: "紹介",
    nav_contact: "お問い合わせ",
    nav_catering: "ケータリング",
    footer_link_home: "ホーム",
    footer_link_menu: "メニュー",
    footer_link_about: "紹介",
    footer_link_contact: "お問い合わせ",
    footer_link_catering: "ケータリング",
    form_error_name: "名前は必須です。",
    form_error_phone: "無効な電話番号です。",
    form_error_date: "日付は必須です。",
    form_error_date_past: "日付は過去にできません。",
    form_error_menu: "メニュー選択は必須です。",
    form_error_total: "最低10人分。",
    notif_success: "ケータリングリクエストが正常に送信されました！すぐにご連絡いたします。",
    notif_cart_empty: "カートが空です。まず商品を追加してください。",
    notif_cart_add: "カートに追加されました",
    notif_cart_stock: "在庫切れ！",
    notif_cart_over: "カートの数量が在庫を超えています！",
    notif_order_name: "お名前を入力してください",
    notif_order_qty: "無効な注文数量",
    notif_order_sent: "注文が正常に送信されました！WhatsAppでご確認ください。",
    notif_payment_redirect: "支払いページにリダイレクトされます。",
    hero_title: "ようこそ",
    hero_subtitle: "2024年から本格的な味で高品質な料理と飲み物を提供しています。",
    about_brand: "私たちの店",
    about_desc1: "ケダイ メイは本格的な味で高品質な料理と飲み物を楽しめる最高の場所です。",
    about_desc2: "常に新鮮な食材と厳選されたレシピを使用しています。",
    about_desc3: "ケダイ メイで快適な雰囲気と親切なサービスをお楽しみください。",
    tab_makanan: "料理",
    tab_minuman: "飲み物",
    tab_snack: "スナック",
    contact_address_label: "住所",
    contact_address: "Jl. Raya Kedai No. 123, Kota Kita",
    contact_phone_label: "電話",
    contact_phone: "087878177527",
    contact_email_label: "メール",
    contact_email: "info@kedaimae.com",
    spicy_not: "辛くない",
    spicy_medium: "普通",
    spicy_hot: "辛い",
    spicy_very_hot: "とても辛い",
    footer_copyright: "&copy; 2025 ケダイ メイ. 無断転載を禁じます。",
  },
  fr: {
    brand_name: "Kedai",
    menu_title: "Notre Menu",
    see_menu: "Voir le menu",
    order_now: "Commander Maintenant",
    about_title: "À propos de nous",
    contact_title: "Contactez-nous",
    search_placeholder: "Rechercher un menu nourriture/boisson/snack...",
    footer_brand: "Kedai Mae",
    footer_desc: "Servir des plats et boissons de qualité au goût authentique depuis 2024.",
    footer_quicklinks: "Liens rapides",
    footer_contact: "Contact",
    catering_title: "Commande de traiteur",
    catering_name_label: "Nom :",
    catering_name_placeholder: "Entrez votre nom",
    catering_phone_label: "Téléphone/WhatsApp :",
    catering_phone_placeholder: "08xxxxxxxxxx",
    catering_event_label: "Type d'événement :",
    catering_event_placeholder: "Ex : Réunion, Séminaire, Anniversaire, etc.",
    catering_date_label: "Date de l'événement :",
    catering_menu_label: "Sélection du menu :",
    catering_menu_placeholder: "Ex : Riz frit 20 portions, Poulet rôti 15 portions, etc.",
    catering_total_label: "Nombre total de portions :",
    catering_total_placeholder: "Minimum 10",
    catering_notes_label: "Notes supplémentaires :",
    catering_notes_placeholder: "Demandes spéciales, allergies, etc. (optionnel)",
    catering_estimasi_label: "Prix estimé (Rp) :",
    catering_submit: "Envoyer la demande de traiteur",
    catering_why_title: "Pourquoi commander un traiteur chez Kedai Mae ?",
    catering_why_1: "✔️ Menu personnalisable selon vos besoins",
    catering_why_2: "✔️ Prix spécial pour les grandes quantités",
    catering_why_3: "✔️ Consultation gratuite menu & portions",
    catering_why_4: "✔️ Idéal pour réunions, bureaux, anniversaires, etc.",
    nav_home: "Accueil",
    nav_menu: "Menu",
    nav_about: "À propos",
    nav_contact: "Contact",
    nav_catering: "Traiteur",
    footer_link_home: "Accueil",
    footer_link_menu: "Menu",
    footer_link_about: "À propos",
    footer_link_contact: "Contact",
    footer_link_catering: "Traiteur",
    form_error_name: "Le nom est requis.",
    form_error_phone: "Numéro de téléphone invalide.",
    form_error_date: "La date est requise.",
    form_error_date_past: "La date ne peut pas être passée.",
    form_error_menu: "La sélection du menu est requise.",
    form_error_total: "Minimum 10 portions.",
    notif_success: "Demande de traiteur envoyée avec succès ! Nous vous contacterons bientôt.",
    notif_cart_empty: "Votre panier est vide. Veuillez d'abord ajouter des articles.",
    notif_cart_add: "ajouté au panier",
    notif_cart_stock: "Rupture de stock !",
    notif_cart_over: "La quantité du panier dépasse le stock !",
    notif_order_name: "Veuillez entrer votre nom",
    notif_order_qty: "Quantité de commande invalide",
    notif_order_sent: "Commande envoyée avec succès ! Veuillez vérifier votre WhatsApp pour confirmation.",
    notif_payment_redirect: "Vous allez être redirigé vers la page de paiement.",
    hero_title: "Bienvenue chez",
    hero_subtitle: "Des plats et boissons de qualité au goût authentique depuis 2024",
    about_brand: "Notre établissement",
    about_desc1: "Kedai Mae est le meilleur endroit pour savourer des plats et boissons de qualité au goût authentique.",
    about_desc2: "Nous utilisons toujours des ingrédients frais et des recettes sélectionnées pour chaque plat.",
    about_desc3: "Profitez d'une ambiance chaleureuse et d'un service amical chez Kedai Mae.",
    tab_makanan: "Plats",
    tab_minuman: "Boissons",
    tab_snack: "Snacks",
    contact_address_label: "Adresse",
    contact_address: "Jl. Raya Kedai No. 123, Kota Kita",
    contact_phone_label: "Téléphone",
    contact_phone: "087878177527",
    contact_email_label: "Email",
    contact_email: "info@kedaimae.com",
    spicy_not: "Pas épicé",
    spicy_medium: "Moyen",
    spicy_hot: "Épicé",
    spicy_very_hot: "Très épicé",
    footer_copyright: "&copy; 2025 Kedai Mae. Tous droits réservés.",
  },
};

function applyTranslation(lang) {
  const dict = window.TRANSLATIONS[lang] || window.TRANSLATIONS['id'];
  // Untuk text
  document.querySelectorAll('[data-translate]').forEach(el => {
    const key = el.getAttribute('data-translate');
    el.textContent = dict[key] || window.TRANSLATIONS['id'][key] || key;
  });
  // Untuk placeholder
  document.querySelectorAll('[data-translate-placeholder]').forEach(el => {
    const key = el.getAttribute('data-translate-placeholder');
    el.placeholder = dict[key] || window.TRANSLATIONS['id'][key] || key;
  });
  // Untuk value (misal button)
  document.querySelectorAll('[data-translate-value]').forEach(el => {
    const key = el.getAttribute('data-translate-value');
    el.value = dict[key] || window.TRANSLATIONS['id'][key] || key;
  });
}

// Event listener untuk selector bahasa
document.addEventListener('DOMContentLoaded', function() {
  const langSwitcher = document.getElementById('lang-switcher');
  let lang = localStorage.getItem('lang') || 'id';
  langSwitcher.value = lang;
  applyTranslation(lang);
  langSwitcher.addEventListener('change', function() {
    lang = this.value;
    localStorage.setItem('lang', lang);
    applyTranslation(lang);
  });
});
